services:
    swd.twig.merge_path_extension:
        class: Swd\AnalyzerBundle\Twig\MergePathExtension
        tags:
            - { name: twig.extension }
        arguments: [ @service_container ]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    generator_manager:
        class:     Swd\AnalyzerBundle\Generator\GeneratorManager
        arguments: [ @doctrine.orm.entity_manager ]

    swd.locale_listener:
        class: Swd\AnalyzerBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    swd.user_locale_listener:
        class: Swd\AnalyzerBundle\EventListener\UserLocaleListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
